USE [master]
GO

/****** Object:  Database [HTTDB]    Script Date: 28.09.2023 14:29:37 ******/
CREATE DATABASE [HTTDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HTTDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HTTDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HTTDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\HTTDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HTTDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HTTDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HTTDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HTTDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HTTDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HTTDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HTTDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HTTDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HTTDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HTTDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HTTDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HTTDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HTTDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HTTDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HTTDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HTTDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HTTDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HTTDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HTTDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HTTDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HTTDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HTTDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HTTDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HTTDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HTTDB] SET  MULTI_USER 
GO

ALTER DATABASE [HTTDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HTTDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HTTDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HTTDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HTTDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HTTDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HTTDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HTTDB] SET  READ_WRITE 
GO

USE [HTTDB]
GO

/****** Object:  Table [dbo].[Categories]    Script Date: 28.09.2023 14:30:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](20) NOT NULL,
	[Description] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [HTTDB]
GO

/****** Object:  Table [dbo].[Products]    Script Date: 28.09.2023 14:30:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[Price] [numeric](18, 0) NOT NULL,
	[InStock] [int] NULL,
	[CategoryId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Products]  WITH CHECK ADD FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([Id])
GO


